### ISSUE TITLE
WebP asset generation not working

### ISSUE THREAD

**Issue by JimCollinson** [adobe-photoshop/generator-assets#423] opened 2016-10-26 13:57 UTC
I've enabled webp but assets are not being generated. I get no errors, but no webp filers either.

Here is what I have in my generator.js file:

`module.exports = {
    "generator-assets":  {
    "webp-enabled": true,
    "use-flite":true,
    "embed-icc-profile":true,
    "icc-profile":"sRGB IEC61966-2.1",
    "use-jpg-encoding":"optimal",
    }
}
`

I'm on Mac OS 10.12.

**Comment by mcilroyc** [comment] 2016-10-26 14:40
@JimCollinson it seems that trailing comma in your snippet above is preventing the options from loading correctly.  Maybe that was just a copy/paste issue.  Regardless, after fixing that, I agree that webp files are not rendering with those configs.  But I do see errors in the log.  I have confirmed that removing several of the options, and thereby forcing the older "ImageMagick" conversion processing, webp works:
```
{"generator-assets": { "webp-enabled": true, "use-jpg-encoding":"optimal" }}
```

This is still a valid issue, but hopefully the above workaround helps.  Assigning to @pineapplespatula since it is a consideration for FLITE.

**Comment by JimCollinson** [comment] 2016-10-26 14:56
Ah, so I can't use FLITE, sRGB profiles *and* webp at the moment?

Kind of a bummer, as I'm trying to automate the output for a huge collection of web assets for a production environment, and they are not up to standard without FLITE etc.

**Comment by mcilroyc** [comment] 2016-10-26 15:02
Sorry, but it seems that at least FLITE is a no go.  Maybe this helps though (?):
```
{"generator-assets": { "webp-enabled": true, "icc-profile":"sRGB IEC61966-2.1", "use-jpg-encoding":"optimal" }}
```
Can you describe how the webp images are "not up to standard"?  That would be helpful for our planning.

**Comment by JimCollinson** [comment] 2016-10-26 15:05
Sorry, I meant the jpegs are not up to standard without FLITE.

Also, how do I specify the quality of the webp, same way as I do for jpg? E.g. `*.webp8`

(BTW, would also be nice to be able to output lossy and lossless webp at the same time).

**Comment by mcilroyc** [comment] 2016-10-26 15:23
Understood, thanks.  
Yes, `webpN` should work to control the quality, where 1 >= N >= 10

You've probably already thought of this, but it seems your only option currently is to change the configuration and do several "runs" of generator-assets.  Painful, I know.

**Comment by JimCollinson** [comment] 2016-10-26 15:24
Yeah, figured that. Not a pleasant option.

**Comment by JimCollinson** [comment] 2016-10-27 10:59
@mcilroyc 

> You've probably already thought of this, but it seems your only option currently is to change the configuration and do several "runs" of generator-assets. Painful, I know.

Do I need to restart photoshop every time I change this config file? Or can I just edit it and then untick/tick generate images for it to take effect?

**Comment by mcilroyc** [comment] 2016-10-27 13:38
@JimCollinson you'll need to restart generator after changing the configs.  That can be done by disabling/enabling generator in the PS prefs (plug-ins tab).  This little tool might help you out because it allows you to change generator options, and then it automatically handles the restarting of generator: https://github.com/adobe-photoshop/generator-panels

**Comment by JimCollinson** [comment] 2016-10-28 12:57
@mcilroyc doesn't seem to work for me, although restarting photoshop does.

I take it that the poor colour reproduction on webp is down to no FLITE and lack of / buggy sRGB output?

cc @pineapplespatula

**Comment by mcilroyc** [comment] 2016-10-28 14:04
@JimCollinson I'm not immediately sure.  What is the color profile of your PSD?  If you'd be willing to post a sample PSD (stripped of anything that shouldn't be public) (or emailed directly to me: "mcilroy at") we could help diagnose.

**Comment by JimCollinson** [comment] 2016-10-28 14:20
@mcilroyc Here you go.


[Klimax DS Black front with Shadow.psd.zip](https://github.com/adobe-photoshop/generator-assets/files/558599/Klimax.DS.Black.front.with.Shadow.psd.zip)

**Comment by JimCollinson** [comment] 2016-10-28 14:25
@mcilroyc In particular, check out the colour of the logo on the display when comparing between my original config settings for jpg/png and the webp output

**Comment by mcilroyc** [comment] 2016-10-28 15:43
I noticed that the logo looks correct for webp-lossless, but not standard webp.  Are you seeing the same?  Note this is with a minimal set of configs: `{"generator-assets": {"webp-enabled":true, "webp-lossless": true}}`

Also, quick note about changing generator configs:  To avoid restarting photoshop you can disable generator (via CMD-K prefs dialog) **and then click OK to close the prefs dialog** ... and then re-open the dialog to enabled generator again.

**Comment by JimCollinson** [comment] 2016-10-31 08:54
I haven't actually tried webp-lossless, but rather I'm comparing webp-lossy to jpg and png: the colours are way off. If there wasn't such a file-size saving, I'd say they were unusable in production.

Also, I find the disabling/enabling generator in prefs method quite flaky; often when generator doing this I can't seem to get it re-generate the assets, even the menu item (File>Generate>Image Assets) is often unresponsive and won't untick/tick. So much so, that its far quicker for me to save my work and restart photoshop.

It'd be splendid if we could have webp working with FLITE... and all save this pain.

**Comment by mcilroyc** [comment] 2016-11-03 14:24
@JimCollinson I'm going to close this issue because I believe the core bug was resolved with https://github.com/adobe-photoshop/generator-core/pull/368

The color issues with webp are still outstanding, but it seems clear that this is an issue within ImageMagick (since the lossless version is fine).  If you disagree, or think we should open a separate issue for that, please let me know.

Unfortunately webp is not yet supported by FLITE, but we have logged that request internally and hope to move to webp+FLITE eventually.

**Closed by mcilroyc** 2016-11-03 14:24 UTC
