### ISSUE TITLE
Non-empty assets can sometimes get incorrectly clipped to document bounds and seem empty

### ISSUE THREAD

**Issue by joelrbrandt** [adobe-photoshop/generator-assets#337] opened 2015-02-17 02:54 UTC
A customer is having a problem generating assets from a file that he has shared with us privately. (If you're an Adobe employee, ask me for access if you don't already have access to our private PSDs.)

In the log, errors like this appear:

```
[error:generator-assets 14:23:18.778 assetmanager.js:367:34] Render failed: notification-nue.png { [Error: Refusing to render pixmap with bounds completely clipped.] outsideDocumentBoundsError: true }
```

However, the asset is not outside of the document bounds.

**Comment by joelrbrandt** [comment] 2015-02-17 02:54
Assigning to @chrisbank since the clipping to bounds code seems to be involved. Feel free to bounce it back if that's a red herring.

**Comment by joelrbrandt** [comment] 2015-02-17 03:00
Look for files with `...generator-assets-issue-337...` in the filename in our shared PSD test files folder.

**Comment by mcilroyc** [comment] 2016-02-05 17:16
kicking over to @pineapplespatula.  I'll assume no progress was made here, but if @chrisbank knows otherwise, he may chime in.

**Comment by pineapplespatula** [comment] 2016-02-29 21:41
I cannot reproduce this. @chadrolfs can you take a shot. ( you can ask me for the file if you dont have access to the OneDrive folder)

**Comment by chadrolfs** [comment] 2016-03-05 00:51
Tested both Mac and Win, CNR on both.  Closing

**Closed by chadrolfs** 2016-03-05 00:51 UTC
Labels: CNR, Rendering
